
GET http://localhost:5000/api/todos
clientKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsemlwdXRyYSIsInBhc3N3b3JkIjoiMTIzIiwiaWF0IjoxNjk5ODk0MzQwLCJleHAiOjE2OTk5ODA3NDB9.32Lxu6h5ud9IqMmonr3cNknuXdR1B43NSTT5hjhkC8A

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "alziputra",
  "password": "123"
}